language: java
jdk: oraclejdk8
sudo: true
dist: trusty

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "dicksonmulli-github"
    token:
      secure: 82b2e868e29286493fb9d76b34ef577b78586c60

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

script:
  - ./mvnw clean install
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

