language: java
jdk: oraclejdk8
sudo: true
dist: trusty

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "dicksonmulli-github"
    token:
      secure: 96c14995883fedb3f029c468a8e8dfa59dbcb062

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

script:
  - ./mvnw clean install
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

