language: java
jdk: oraclejdk8


addons:
  sonarcloud:
    organization: "dicksonmulli-github"
    token:
      secure: 96c14995883fedb3f029c468a8e8dfa59dbcb062

sudo: required

services:
  - docker

script:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

